[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"

# The title and description fields are primarily for displaying extension info in UI
title = "Extension for reading CSV file"
description="This extension is to read a CSV file and then display elements (cubes/quad/...) at the XYZ given in the CSV file, + color if any. For now CSV files contain X,Y,Z and cluster keywords"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"
changelog="docs/CHANGELOG.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Other"

# Keywords for the extension
keywords = ["kit", "example", "CSV"]

# Preview image. Folder named "data" automatically goes in git lfs (see .gitattributes file).
preview_image = "data/OV_CSVReader_WhatToExpect.png"
icon = "data/CSV_reader_ico.png"

# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}

# Main python module this extension provides, it will be publicly available as "import omni.hello.world".
[[python.module]]
name = "omni.csv.reader"
